# Generated by Django 3.2.6 on 2023-03-16 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('n_name', models.CharField(max_length=30, verbose_name='国家名称')),
            ],
            options={
                'verbose_name': '国家表',
                'verbose_name_plural': '国家表',
                'db_table': 't_nation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=30, verbose_name='省份名称')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_list', to='basic_info.nation')),
            ],
            options={
                'verbose_name': '省份表',
                'verbose_name_plural': '省份表',
                'db_table': 't_Province',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30, verbose_name='省份名称')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_list', to='basic_info.province')),
            ],
            options={
                'verbose_name': '城市表',
                'verbose_name_plural': '城市表',
                'db_table': 't_city',
                'ordering': ['id'],
            },
        ),
    ]
