# Generated by Django 3.2.6 on 2023-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='nation',
            table='nation',
        ),
        migrations.AlterModelTable(
            name='province',
            table='Province',
        ),
    ]
