# Generated by Django 3.2.6 on 2023-03-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_auto_20230316_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='province',
            table='province',
        ),
    ]
