# Generated by Django 3.2.6 on 2023-03-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0004_goodsinventorymodel_goodsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='delete_flag',
            field=models.BooleanField(default=False, max_length=1, verbose_name='启动和禁用标记'),
        ),
    ]
