# Generated by Django 3.2.6 on 2023-03-23 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods_info', '0005_goodsmodel_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinventorymodel',
            name='creat_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinventorymodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
