# Generated by Django 3.2.6 on 2023-03-08 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='排序数字')),
                ('url', models.CharField(blank=True, max_length=256, null=True, verbose_name='菜单访问的url地址')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='菜单访问的url地址')),
                ('delete_flag', models.CharField(default='0', max_length=1, verbose_name='删除的标记')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp_system.menumodel')),
            ],
            options={
                'verbose_name': '功能菜单表',
                'verbose_name_plural': '功能菜单表',
                'db_table': 't_menu',
            },
        ),
    ]
