# Generated by Django 3.2.6 on 2023-03-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0002_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='菜单名称'),
        ),
    ]
