# Generated by Django 3.2.6 on 2023-03-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0003_alter_menumodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('is_menu', models.BooleanField(default=True, verbose_name='是否为菜单')),
                ('method', models.CharField(blank=True, choices=[('POST', '增'), ('DELETE', '删'), ('PUT', '改'), ('PATCH', '改局部'), ('GET', '查')], default='', max_length=8, verbose_name='操作')),
                ('path', models.CharField(blank=True, max_length=256, null=True, verbose_name='访问url地址')),
                ('desc', models.CharField(blank=True, max_length=512, null=True, verbose_name='权限的描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'db_table': 't_permissions',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='menumodel',
            options={'ordering': ['number'], 'verbose_name': '功能菜单表', 'verbose_name_plural': '功能菜单表'},
        ),
        migrations.CreateModel(
            name='RolesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('permissions', models.ManyToManyField(blank=True, db_table='t_roles_permissions', to='erp_system.PermissionsModel', verbose_name='角色的权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 't_roles',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='permissionsmodel',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions_list', to='erp_system.menumodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='roles',
            field=models.ManyToManyField(blank=True, db_table='t_users_roles', to='erp_system.RolesModel', verbose_name='用户所有的角色'),
        ),
    ]
