# Generated by Django 3.2.6 on 2023-03-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0004_auto_20230309_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='部门名称')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='部门地址')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='erp_system.deptmodel', verbose_name='部门从属(上级)部门')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'db_table': 't_dept',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_system.deptmodel', verbose_name='所属部门'),
        ),
    ]
