# Generated by Django 3.2.6 on 2023-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_system', '0005_auto_20230310_2337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ['id'], 'verbose_name': '系统用户表', 'verbose_name_plural': '系统用户表'},
        ),
    ]
